/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it351.key.assignment.unit.pkg3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jimro
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        
        initComponents();
        custIDError.setVisible(false);
        custNameError.setVisible(false);
        custLoginError.setVisible(false);
        custPasswordError.setVisible(false);
        prodIDError.setVisible(false);
        prodNameError.setVisible(false);
        prodDescriptionError.setVisible(false);
        prodCostError.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        custPanel = new javax.swing.JPanel();
        displayCustomerButton = new javax.swing.JButton();
        jCustPane2 = new javax.swing.JScrollPane();
        customersTextArea = new javax.swing.JTextArea();
        custIdTextField = new javax.swing.JTextField();
        custIdTFLabel = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        custNameTFLabel = new javax.swing.JLabel();
        custLoginTextField = new javax.swing.JTextField();
        custLoginTFLabel = new javax.swing.JLabel();
        custPasswordTextField = new javax.swing.JTextField();
        custPasswordTFLabel = new javax.swing.JLabel();
        custUpdateButton = new javax.swing.JButton();
        custCreateButton = new javax.swing.JButton();
        custDeleteButton = new javax.swing.JButton();
        custDeleteTextField = new javax.swing.JTextField();
        custDeleteTFLabel = new javax.swing.JLabel();
        custIDError = new javax.swing.JLabel();
        custNameError = new javax.swing.JLabel();
        custLoginError = new javax.swing.JLabel();
        custPasswordError = new javax.swing.JLabel();
        prodPanel = new javax.swing.JPanel();
        displayProductButton = new javax.swing.JButton();
        jProdScrollPane1 = new javax.swing.JScrollPane();
        productsTextArea = new javax.swing.JTextArea();
        prodIdTextField = new javax.swing.JTextField();
        prodIdTFLabel = new javax.swing.JLabel();
        prodNameTextField = new javax.swing.JTextField();
        prodNameTFLable = new javax.swing.JLabel();
        prodDescriptionTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        prodCostTextField = new javax.swing.JTextField();
        prodCostTFLabel = new javax.swing.JLabel();
        prodUpdateButton = new javax.swing.JButton();
        prodCreateButton = new javax.swing.JButton();
        prodDeleteButton = new javax.swing.JButton();
        prodDeleteTextField = new javax.swing.JTextField();
        prodDeleteTFLabel = new javax.swing.JLabel();
        prodIDError = new javax.swing.JLabel();
        prodNameError = new javax.swing.JLabel();
        prodDescriptionError = new javax.swing.JLabel();
        prodCostError = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        quitButton = new javax.swing.JButton();

        jFrame1.setTitle("Jim Roebuck IT351 IP3");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jim Roebuck IT351 IP3");

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        custPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        displayCustomerButton.setText("Display Customers");
        displayCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCustomerButtonActionPerformed(evt);
            }
        });

        customersTextArea.setColumns(20);
        customersTextArea.setRows(5);
        jCustPane2.setViewportView(customersTextArea);

        custIdTFLabel.setText("Cust ID");

        custNameTFLabel.setText("Name");

        custLoginTFLabel.setText("Login");

        custPasswordTFLabel.setText("Password");

        custUpdateButton.setText("Update");
        custUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custUpdateButtonActionPerformed(evt);
            }
        });

        custCreateButton.setText("Create");
        custCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custCreateButtonActionPerformed(evt);
            }
        });

        custDeleteButton.setText("Delete");
        custDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custDeleteButtonActionPerformed(evt);
            }
        });

        custDeleteTFLabel.setText("Delete Records for Customer ID:");

        custIDError.setForeground(new java.awt.Color(255, 0, 50));
        custIDError.setText("Cust ID Required");

        custNameError.setForeground(new java.awt.Color(255, 0, 50));
        custNameError.setText("Name Required");

        custLoginError.setForeground(new java.awt.Color(255, 0, 50));
        custLoginError.setText("Login Required");

        custPasswordError.setForeground(new java.awt.Color(255, 0, 50));
        custPasswordError.setText("Password Required");

        javax.swing.GroupLayout custPanelLayout = new javax.swing.GroupLayout(custPanel);
        custPanel.setLayout(custPanelLayout);
        custPanelLayout.setHorizontalGroup(
            custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCustPane2)
                    .addGroup(custPanelLayout.createSequentialGroup()
                        .addComponent(displayCustomerButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(custPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(custIdTFLabel)
                    .addComponent(custNameTFLabel)
                    .addComponent(custLoginTFLabel)
                    .addComponent(custPasswordTFLabel)
                    .addComponent(custCreateButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custPanelLayout.createSequentialGroup()
                        .addComponent(custIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custIDError))
                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(custPanelLayout.createSequentialGroup()
                        .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(custLoginTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custPasswordTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custLoginError)
                            .addComponent(custPasswordError)))
                    .addComponent(custUpdateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 311, Short.MAX_VALUE)
                        .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(custDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, custPanelLayout.createSequentialGroup()
                                .addComponent(custDeleteTFLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(custDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))
                    .addGroup(custPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(custNameError)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        custPanelLayout.setVerticalGroup(
            custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(custPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayCustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCustPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custIdTFLabel)
                    .addComponent(custIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custNameTFLabel)
                    .addComponent(custNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custLoginTFLabel)
                    .addComponent(custLoginError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custDeleteTFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(custPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(custPasswordTFLabel)
                        .addComponent(custPasswordError)))
                .addGap(18, 18, 18)
                .addGroup(custPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custCreateButton)
                    .addComponent(custDeleteButton)
                    .addComponent(custUpdateButton))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Cutomer", custPanel);

        prodPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        displayProductButton.setText("Display Products");
        displayProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayProductButtonActionPerformed(evt);
            }
        });

        productsTextArea.setColumns(20);
        productsTextArea.setRows(5);
        jProdScrollPane1.setViewportView(productsTextArea);

        prodIdTFLabel.setText("Product ID");

        prodNameTFLable.setText("Name");

        jLabel2.setText("Description");

        prodCostTFLabel.setText("Cost");

        prodUpdateButton.setText("Update");
        prodUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodUpdateButtonActionPerformed(evt);
            }
        });

        prodCreateButton.setText("Create");
        prodCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCreateButtonActionPerformed(evt);
            }
        });

        prodDeleteButton.setText("Delete");
        prodDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodDeleteButtonActionPerformed(evt);
            }
        });

        prodDeleteTFLabel.setForeground(new java.awt.Color(255, 0, 0));
        prodDeleteTFLabel.setText("Delete Records for Product ID:");

        prodIDError.setForeground(new java.awt.Color(255, 0, 50));
        prodIDError.setText("Prod. ID Required");

        prodNameError.setForeground(new java.awt.Color(255, 0, 50));
        prodNameError.setText(" Name Required");

        prodDescriptionError.setForeground(new java.awt.Color(255, 0, 50));
        prodDescriptionError.setText("Description Required");

        prodCostError.setForeground(new java.awt.Color(255, 0, 50));
        prodCostError.setText("Product Cost Required");

        javax.swing.GroupLayout prodPanelLayout = new javax.swing.GroupLayout(prodPanel);
        prodPanel.setLayout(prodPanelLayout);
        prodPanelLayout.setHorizontalGroup(
            prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProdScrollPane1)
                    .addGroup(prodPanelLayout.createSequentialGroup()
                        .addComponent(displayProductButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(prodPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(prodPanelLayout.createSequentialGroup()
                        .addComponent(prodCreateButton)
                        .addGap(153, 153, 153)
                        .addComponent(prodUpdateButton))
                    .addGroup(prodPanelLayout.createSequentialGroup()
                        .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodIdTFLabel)
                            .addComponent(prodNameTFLable)
                            .addComponent(jLabel2)
                            .addComponent(prodCostTFLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(prodPanelLayout.createSequentialGroup()
                                .addComponent(prodCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prodCostError))
                            .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(prodPanelLayout.createSequentialGroup()
                                    .addComponent(prodIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(prodIDError))
                                .addComponent(prodNameTextField)
                                .addComponent(prodDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prodPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                        .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prodPanelLayout.createSequentialGroup()
                                .addComponent(prodDeleteTFLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prodDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prodDeleteButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(82, 82, 82))
                    .addGroup(prodPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodDescriptionError)
                            .addComponent(prodNameError))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        prodPanelLayout.setVerticalGroup(
            prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProdScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodIdTFLabel)
                    .addComponent(prodIDError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodNameTFLable)
                    .addComponent(prodNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(prodDescriptionError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prodDeleteTFLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prodCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prodCostTFLabel)
                        .addComponent(prodCostError)))
                .addGap(18, 18, 18)
                .addGroup(prodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodCreateButton)
                    .addComponent(prodDeleteButton)
                    .addComponent(prodUpdateButton))
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Product", prodPanel);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 24)); // NOI18N
        jLabel1.setText("DATABASE MANAGER");

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        int quit = JOptionPane.showConfirmDialog(this, "Quit?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);

        if (quit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if (quit == JOptionPane.NO_OPTION) {

        }


    }//GEN-LAST:event_quitButtonActionPerformed

    private void displayCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCustomerButtonActionPerformed
        
        customersTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            CustomerDAO cdao = new CustomerDAO(conn);
            
            
            for(Customer c: cdao.getAll()){
                
                System.out.println(c);
                customersTextArea.append(c.toString() + "\n");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            customersTextArea.append("Not connected to SQL Database");
        }
        
        
    }//GEN-LAST:event_displayCustomerButtonActionPerformed

    private void displayProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayProductButtonActionPerformed
         productsTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            ProductDAO pdao = new ProductDAO(conn);
            
            
            for(Product p: pdao.getAll()){
                
                System.out.println(p);
                productsTextArea.append(p.toString() + "\n");
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            productsTextArea.append("Not connected to SQL Database");
        }
        
    }//GEN-LAST:event_displayProductButtonActionPerformed

    private void prodCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCreateButtonActionPerformed
        productsTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Product p = new Product();
        boolean allInput = true;

        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            ProductDAO pdao = new ProductDAO(conn);

            String id = prodIdTextField.getText();
            if (id.trim().length() == 0) {
                prodIDError.setVisible(true);
                allInput = false;
                ;
            } else {
                p.setId(Integer.parseInt(id));
            }

            String name = prodNameTextField.getText();
            if (name.trim().length() == 0) {
                prodNameError.setVisible(true);
                allInput = false;
            } else {
                p.setName(name);
            }

            String description = prodDescriptionTextField.getText();
            if (description.trim().length() == 0) {
                prodDescriptionError.setVisible(true);
                allInput = false;
            } else {
                p.setDescription(description);
            }

            String price = prodCostTextField.getText();
            if (price.trim().length() == 0) {
                prodCostError.setVisible(true);
                allInput = false;
            } else {
                p.setPrice(Double.parseDouble(price));
            }

            if (allInput == true) {
                pdao.create(p);
                
                productsTextArea.setText("");
                prodIdTextField.setText("");
                prodNameTextField.setText("");
                prodDescriptionError.setText("");
                prodCostTextField.setText("");

                productsTextArea.setText("Product Successfully Added" + "\n"
                        + p.toString());
            }

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            productsTextArea.append("Not connected to SQL Database");
        }
            
        
        
    }//GEN-LAST:event_prodCreateButtonActionPerformed

    private void custCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custCreateButtonActionPerformed
        customersTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Customer c = new Customer();
        boolean allInput = true;
        
        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            CustomerDAO cdao = new CustomerDAO(conn);
            
            String id = custIdTextField.getText();
            if(id.trim().length() == 0){
                custIDError.setVisible(true);
                allInput = false;                
            } else {     
                c.setId(Integer.parseInt(id));
                custIDError.setVisible(false);
            }
            
            String name = custNameTextField.getText();
            if(name.trim().length() == 0){
                custNameError.setVisible(true);
                allInput = false;                
            } else{
                 c.setName(name);
                 custNameError.setVisible(false);
            }
            
            String login = custLoginTextField.getText();
            if(login.trim().length() == 0){
                custLoginError.setVisible(true);
                allInput = false;                
            }else{
                c.setLogin(login);
                custLoginError.setVisible(false);
            }
            
            String password = custPasswordTextField.getText();
            if(password.trim().length() == 0){
                custPasswordError.setVisible(true);
                allInput = false;                
            } else{
                c.setPassword(password);
                custPasswordError.setVisible(false);
            }
            
            if(allInput == true){
            cdao.create(c);
           

            customersTextArea.setText("");
            custIdTextField.setText("");
            custNameTextField.setText("");
            custLoginTextField.setText("");
            custPasswordTextField.setText("");
            
            customersTextArea.setText("Customer Successfully Added" + "\n" +
                    c.toString());
            
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            customersTextArea.append("Not connected to SQL Database");
        }
            
        
       
    }//GEN-LAST:event_custCreateButtonActionPerformed

      
    private void custUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custUpdateButtonActionPerformed
        customersTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Customer c = new Customer();
        boolean allInput = true;

        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            CustomerDAO cdao = new CustomerDAO(conn);

            String id = custIdTextField.getText();
            if (id.trim().length() == 0) {
                custIDError.setVisible(true);
                allInput = false;
            } else {
                c.setId(Integer.parseInt(id));
                custIDError.setVisible(false);
            }

            String name = custNameTextField.getText();
            if (name.trim().length() == 0) {
                custNameError.setVisible(true);
                allInput = false;
            } else {
                c.setName(name);
                custNameError.setVisible(false);
            }

            String login = custLoginTextField.getText();
            if (login.trim().length() == 0) {
                custLoginError.setVisible(true);
                allInput = false;
            } else {
                c.setLogin(login);
                custLoginError.setVisible(false);
            }

            String password = custPasswordTextField.getText();
            if (password.trim().length() == 0) {
                custPasswordError.setVisible(true);
                allInput = false;
            } else {
                c.setPassword(password);
                custPasswordError.setVisible(false);
            }

            if (allInput == true) {
                cdao.update(c);

                customersTextArea.setText("");
                custIdTextField.setText("");
                custNameTextField.setText("");
                custLoginTextField.setText("");
                custPasswordError.setText("");


                customersTextArea.setText("Customer Successfully Updated" + "\n"
                        + c.toString());
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            customersTextArea.append("Not connected to SQL Database");
        }


        
    }//GEN-LAST:event_custUpdateButtonActionPerformed

    private void prodUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodUpdateButtonActionPerformed
        productsTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Product p = new Product();
        boolean allInput = true;

        try {
            Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
            ProductDAO pdao = new ProductDAO(conn);

            String id = prodIdTextField.getText();
            if (id.trim().length() == 0) {
                prodIDError.setVisible(true);
                allInput = false;
            } else {
                p.setId(Integer.parseInt(id));
                prodIDError.setVisible(false);
            }

            String name = prodNameTextField.getText();
            if (name.trim().length() == 0) {
                prodNameError.setVisible(true);
                allInput = false;
            } else {
                p.setName(name);
                prodNameError.setVisible(false);
            }

            String description = prodDescriptionTextField.getText();
            if (description.trim().length() == 0) {
                prodDescriptionError.setVisible(true);
                allInput = false;
            } else {
                p.setDescription(description);
                prodDescriptionError.setVisible(false);
            }

            String price = prodCostTextField.getText();
            if (price.trim().length() == 0) {
                prodCostError.setVisible(true);
                allInput = false;
            } else {
                p.setPrice(Double.parseDouble(price));
                prodCostError.setVisible(false);
            }

            if (allInput == true) {
                pdao.update(p);

                productsTextArea.setText("");
                prodIdTextField.setText("");
                prodNameTextField.setText("");
                prodDescriptionError.setText("");
                prodCostTextField.setText("");

                productsTextArea.setText("Product Successfully Updated" + "\n"
                        + p.toString());
            }

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            productsTextArea.append("Not connected to SQL Database");
        }


    }//GEN-LAST:event_prodUpdateButtonActionPerformed

    private void custDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custDeleteButtonActionPerformed
        customersTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Customer c = new Customer();
        
        try{
        Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
        
        CustomerDAO cdao = new CustomerDAO(conn);
        
        String id = custDeleteTextField.getText();
        
        if(id.trim().length() == 0) {
            System.out.println("Not Developed Yet - Exception GUI Messages");
                //No Data GUI message
        } else {
            c.setId(Integer.parseInt(id));
            customersTextArea.append("Customer Record Deleted: " +"\n");
            cdao.delete(c);
            System.out.println("Customer " + c.getId() + " record deleted.");
        }
            
        }catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            productsTextArea.append("Not connected to SQL Database");
        
        
        }
    }//GEN-LAST:event_custDeleteButtonActionPerformed

    private void prodDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodDeleteButtonActionPerformed
        productsTextArea.setText("");
        String url = "jdbc:mysql://localhost:3306/sales";
        Product p = new Product();
        
        
         try{
        Connection conn = DriverManager.getConnection(url, "ctuonline", "student");        
        ProductDAO pdao = new ProductDAO(conn);
        
        String id = prodDeleteTextField.getText();
        
        if(id.trim().length() == 0) {
            System.out.println("Not Developed Yet - Exception GUI Messages");
                //No Data GUI message
        } else {
            p.setId(Integer.parseInt(id));
            productsTextArea.append("Record Deleted: " +"\n");
            pdao.delete(p);
            System.out.println("Product " + p.getId() + " record deleted.");
        }
            
        }catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            productsTextArea.append("Not connected to SQL Database");
        
        
        }
    }//GEN-LAST:event_prodDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        
        String url = "jdbc:mysql://localhost:3306/sales";
        Connection conn = DriverManager.getConnection(url, "ctuonline", "student");
        

        CustomerDAO cdao = new CustomerDAO(conn);
        ProductDAO pdao = new ProductDAO(conn);

        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custCreateButton;
    private javax.swing.JButton custDeleteButton;
    private javax.swing.JLabel custDeleteTFLabel;
    private javax.swing.JTextField custDeleteTextField;
    private javax.swing.JLabel custIDError;
    private javax.swing.JLabel custIdTFLabel;
    private javax.swing.JTextField custIdTextField;
    private javax.swing.JLabel custLoginError;
    private javax.swing.JLabel custLoginTFLabel;
    private javax.swing.JTextField custLoginTextField;
    private javax.swing.JLabel custNameError;
    private javax.swing.JLabel custNameTFLabel;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JPanel custPanel;
    private javax.swing.JLabel custPasswordError;
    private javax.swing.JLabel custPasswordTFLabel;
    private javax.swing.JTextField custPasswordTextField;
    private javax.swing.JButton custUpdateButton;
    private javax.swing.JTextArea customersTextArea;
    private javax.swing.JButton displayCustomerButton;
    private javax.swing.JButton displayProductButton;
    private javax.swing.JScrollPane jCustPane2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jProdScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel prodCostError;
    private javax.swing.JLabel prodCostTFLabel;
    private javax.swing.JTextField prodCostTextField;
    private javax.swing.JButton prodCreateButton;
    private javax.swing.JButton prodDeleteButton;
    private javax.swing.JLabel prodDeleteTFLabel;
    private javax.swing.JTextField prodDeleteTextField;
    private javax.swing.JLabel prodDescriptionError;
    private javax.swing.JTextField prodDescriptionTextField;
    private javax.swing.JLabel prodIDError;
    private javax.swing.JLabel prodIdTFLabel;
    private javax.swing.JTextField prodIdTextField;
    private javax.swing.JLabel prodNameError;
    private javax.swing.JLabel prodNameTFLable;
    private javax.swing.JTextField prodNameTextField;
    private javax.swing.JPanel prodPanel;
    private javax.swing.JButton prodUpdateButton;
    private javax.swing.JTextArea productsTextArea;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
